version: '4.23.0'
services:
  postgres-db:
    image: postgres:16
    networks:
      - appnet
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPassword
    ports:
      - '5432:5432'
  app:
      depends_on:
        - 'postgres-db'
      environment:
       - DATABASE_URL=postgresql://testUser:testPassword@postgres-db:5432/mydb?schema=public
      build: 
        dockerfile: ./Dockerfile.test
      ports:
          - '3000:3000'
      networks:
          - appnet      

networks:
  appnet:
    driver: bridge

