version: '4.23.0'
services:
    app:
        build: .
        ports:
            - '3000:3000'
        networks:
            - url-shortener_appnet

networks:
    url-shortener_appnet:
        external: true
